version: "3.9"

services:
  backend:
    build: ./backend
    container_name: excel-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/data
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: excel-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: excel_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: excel-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
